### ISSUE TITLE
Problem with CreateStack algorithm

### ISSUE THREAD

**Issue by PedroVenancio** [DHI-GRAS/processing_gpf#20]
I'm having problems with CreateStack algorithm.

When I add CreateStack to a new model in QGIS Processing, and try to save the model, I get:

An error has occurred while executing Python code:

> AttributeError: 'NoneType' object has no attribute 'setValue'
> Traceback (most recent call last):
>   File "/home/pedro/QGIS_2_18_2/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 252, in save
>     self.saveModel(False)
>   File "/home/pedro/.qgis2/python/plugins/processing_gpf/GPFModelerDialog.py", line 145, in saveModel
>     text = self.alg.toXml()
>   File "/home/pedro/.qgis2/python/plugins/processing_gpf/GPFModelerAlgorithm.py", line 109, in toXml
>     alg.algorithm.getParameterFromName("sourceProduct").setValue(self.algs[param.alg].algorithm.nodeID)
> AttributeError: 'NoneType' object has no attribute 'setValue'
> 
> Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
> QGIS version: 2.18.2 Las Palmas, exported

Using CreateStack algorithm by itself, with two input images, I get:

> Algorithm Create Stack starting...
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Loading external tools...
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s1tbx
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/rstb
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/probavbox
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s2tbx
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/s3tbx
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/smos
> INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /home/pedro/snap/java
> SEVERE: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Failed scan for Tools descriptors: I/O problem: /home/pedro/snap/java
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> at java.util.ArrayList.get(ArrayList.java:429)
> at org.esa.snap.core.gpf.internal.OperatorContext.updatePropertyDescriptors(OperatorContext.java:1131)
> at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:483)
> at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:273)
> at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:387)
> at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:77)
> at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:195)
> at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:178)
> at org.esa.snap.core.gpf.graph.GraphContext.initOutput(GraphContext.java:162)
> at org.esa.snap.core.gpf.graph.GraphContext.(GraphContext.java:91)
> at org.esa.snap.core.gpf.graph.GraphContext.(GraphContext.java:64)
> at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:130)
> at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:84)
> at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:498)
> at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:346)
> at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:245)
> at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:146)
> at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:118)
> at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
> at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
> at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
> at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
> at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
> at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
> 
> Error: Index: 0, Size: 0
> Loading resulting layers
> 
> The following layers were not correctly generated.
> Output Image
> You can check the log messages to find more information about the execution of the algorithm

Can this be a local problem? The other algorithms are working fine.

I'm using QGIS 2.18.2 (self compiled) and SNAP 5.0 on Linux Mint 18.

**Comment by PedroVenancio** [comment]
Fixed in #24 

Thank you very much Rado!
